---
abstract: 'Use Math::Pari for Math::BigInt routines'
author:
  - 'Original Math::BigInt::Pari written by Benjamin Trott 2001, L<ben@rhumba.pair.com>.'
  - 'Benjamin Trott <ben@rhumba.pair.com>, Tels <nospam-abuse@bloodgate.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.62
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-BigInt-Pari
no_index:
  directory:
    - inc
    - t
requires:
  Math::BigInt: 1.90
  Math::Pari: 2.010709
  perl: 5.006002
resources:
  license: http://dev.perl.org/licenses/
version: 1.14
